on: [push]

jobs:
  deploy_job:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      uses: actions/checkout@v2
      - name: Deploy files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.STAGING_SERVER_HOST }}
        port: ${{ secrets.STAGING_SERVER_PORT }}
        username: ${{ secrets.STAGING_SERVER_USERNAME }}
        password: ${{ secrets.STAGING_SERVER_PASSWORD }}
        remote_path: ${{ secrets.STAGING_SERVER_PATH }}
        local_path: './*'
        sftp_only: true